spring:
  h2:
    console:
      enabled: true
    port: 9092
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: